# Generated by Django 6.0.2 on 2026-09-24 08:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=150)),
                ('question', models.CharField(max_length=255)),
                ('fonctionnalite', models.CharField(choices=[('general', 'Général'), ('transactions', 'Suivi des transactions'), ('compte_a_rebours', 'Compte à rebours'), ('epargne', 'Épargne / Objectifs'), ('dettes', 'Dettes et crédits')], max_length=30)),
                ('type_reponse', models.CharField(choices=[('satisfaction', '👍 / 😐 / 👎'), ('choix', 'Choix multiple'), ('texte', 'Texte libre')], default='satisfaction', max_length=15)),
                ('niveau', models.PositiveSmallIntegerField(choices=[(1, 'Niveau 1 — ultra rapide'), (2, 'Niveau 2 — précision'), (3, 'Niveau 3 — commentaire libre')], default=1)),
                ('declenchee_par_reponse', models.CharField(blank=True, help_text="Valeur de réponse du parent qui déclenche cette question (ex: 'non').", max_length=30)),
                ('options_choix', models.JSONField(blank=True, default=list, help_text="Options pour type_reponse='choix', ex: ['Je ne comprends pas', 'C'est compliqué'].")),
                ('seuil_utilisations', models.PositiveSmallIntegerField(default=1, help_text="Nombre d'utilisations de la fonctionnalité avant de proposer cette question.")),
                ('delai_jours_inscription', models.PositiveSmallIntegerField(default=0, help_text="Jours après l'inscription avant de proposer cette question (0 = pas de contrainte).")),
                ('active', models.BooleanField(default=True)),
                ('priorite', models.PositiveSmallIntegerField(default=0, help_text='Plus élevé = affiché en priorité.')),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('question_parent', models.ForeignKey(blank=True, help_text='Question de niveau supérieur qui déclenche celle-ci (ex: niveau 2 après un 👎 au niveau 1).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_enfants', to='feedback.feedbackquestion')),
            ],
            options={
                'ordering': ['-priorite', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reponse', models.CharField(max_length=100)),
                ('commentaire', models.TextField(blank=True)),
                ('version_application', models.CharField(blank=True, max_length=20)),
                ('date_reponse', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='feedback.feedbackquestion')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_reponse'],
            },
        ),
        migrations.CreateModel(
            name='FeatureUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonctionnalite', models.CharField(choices=[('general', 'Général'), ('transactions', 'Suivi des transactions'), ('compte_a_rebours', 'Compte à rebours'), ('epargne', 'Épargne / Objectifs'), ('dettes', 'Dettes et crédits')], max_length=30)),
                ('compteur', models.PositiveIntegerField(default=0)),
                ('derniere_utilisation', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages_fonctionnalites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('utilisateur', 'fonctionnalite'), name='unique_usage_par_utilisateur_et_fonctionnalite')],
            },
        ),
        migrations.CreateModel(
            name='FeedbackAffichage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_affichage', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_affiches', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affichages', to='feedback.feedbackquestion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('utilisateur', 'question'), name='unique_affichage_par_utilisateur_et_question')],
            },
        ),
    ]
