# Generated by Django 6.1.1 on 2026-09-16 16:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_complet', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('frequence_revenu', models.CharField(choices=[('mensuelle', 'Mensuelle'), ('quinzaine', 'Quinzaine'), ('hebdomadaire', 'Hebdomadaire')], default='mensuelle', max_length=20)),
                ('date_paie_habituelle', models.PositiveSmallIntegerField(default=25)),
                ('devise', models.CharField(choices=[('XAF', 'XAF'), ('XOF', 'XOF'), ('USD', 'USD')], default='XAF', max_length=5)),
                ('statut_abonnement', models.CharField(choices=[('essai', 'Essai'), ('gratuit', 'Gratuit'), ('payant', 'Payant')], default='essai', max_length=15)),
                ('date_fin_essai', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('revenu', 'Revenu'), ('depense', 'Dépense')], max_length=10)),
                ('icone', models.CharField(blank=True, max_length=40)),
                ('est_predefinie', models.BooleanField(default=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories_personnelles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Catégories',
                'ordering': ['type', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Dette',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sens', models.CharField(choices=[('je_dois', 'Je dois'), ('on_me_doit', 'On me doit')], max_length=15)),
                ('personne', models.CharField(max_length=150)),
                ('montant_initial', models.DecimalField(decimal_places=2, max_digits=14)),
                ('montant_restant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date_creation', models.DateField(default=django.utils.timezone.now)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('solde', 'Soldé'), ('en_retard', 'En retard')], default='en_cours', max_length=15)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectifEpargne',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('montant_cible', models.DecimalField(decimal_places=2, max_digits=14)),
                ('montant_actuel', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('date_cible', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('atteint', 'Atteint'), ('abandonne', 'Abandonné')], default='en_cours', max_length=15)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs_epargne', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContributionEpargne',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('objectif_epargne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='finances.objectifepargne')),
            ],
        ),
        migrations.CreateModel(
            name='RemboursementDette',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('dette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='finances.dette')),
            ],
        ),
        migrations.CreateModel(
            name='SourceRevenu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('montant_attendu', models.DecimalField(decimal_places=2, max_digits=14)),
                ('frequence', models.CharField(choices=[('mensuelle', 'Mensuelle'), ('quinzaine', 'Quinzaine'), ('hebdomadaire', 'Hebdomadaire')], default='mensuelle', max_length=20)),
                ('jour_habituel', models.PositiveSmallIntegerField(default=25)),
                ('dernier_montant_recu', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('dernier_date_recue', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources_revenu', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('type', models.CharField(choices=[('revenu', 'Revenu'), ('depense', 'Dépense')], max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('canal_declaratif', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('banque', 'Banque'), ('autre', 'Autre')], default='cash', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finances.categorie')),
                ('source_revenu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finances.sourcerevenu')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-cree_le'],
            },
        ),
        migrations.AddConstraint(
            model_name='categorie',
            constraint=models.UniqueConstraint(fields=('utilisateur', 'nom', 'type'), name='unique_categorie_par_utilisateur_et_type'),
        ),
    ]
