# Generated by Django 6.0.2 on 2026-10-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='statut',
            field=models.CharField(choices=[('recue', 'Reçue'), ('prevue', 'Prévue')], default='recue', max_length=10),
        ),
    ]
